version: "3"

services:
  java:
    build: .
    volumes:
      - .:/home/leandro/app
    container_name: java
    image: openjdk
    networks:
      - codejs

  db:
    image: mysql-8.0.23
    build: ./.docker/mysql
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=maluko-doido
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3366:3306"
    depends_on:
      - java
    networks:
      - codejs

networks:
  codejs:
    driver: bridge
